server:
  port: 8888

spring:
  application:
    name: takeaway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reading?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: "161729"
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  redis:
    host: localhost
    port: 6379
    password: ""
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #缓存过期时间

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 标注Mybatis配置文件的位置
  #config-location: classpath:mybatis-config.xml
  # 标注待解析的mapper的xml文件位置
  #mapper-locations: classpath:mapper/*.xml
  # 标注实体类位置
  type-aliases-package: com.example.entity
  # 开启mybatis驼峰式命名规则自动转换
alipay:
  app-id: 9021000144613928
  app-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCOlSJrsTuxksc5eOvJRD5tJHsq1xfSduz6ynghVQYTcKbL1bbJkYdZUUZLBeBDWlxcBaycHp2eXjiCzORqQb0NK51nM/jSEB2atoZYTpFzIBjMaISUYwZjl7rlyh10UnuD64BJEPmNR85QyDisvKoAK6Mf8ezRdEc/ApCLjEv5xp7gC5f93Y6cHCO8GfPdGUezNT5HfZqZDBMLiupbeZL864aRR8pSKy2mbiJZaZdrd20XQblYyoKZ04yajiBuYiyqiLk6XY20PCTOInJKzyzA5dXZyCOY411oa/qoT1HQjGYCZnB4CNMPcS0QZEYV/edNxrztys4SIgk+mM7h6OYRAgMBAAECggEAU0KnLPf8Ab/Scq84EPm28okBG40rLg2gaPrel6hMugFohVMxQBepT/Dz+U9fHDWiBWKS3z/Jjvc6TLdVEu98dDpp2iAxRol+oB/B58NJkE7H7GWENhp1Wqb5zsHt3UVlNy3IZeJxt5ycz/N7lPM+2oag5UCip9Uc3aCjw7mTjDEbvWEzeKoKiPsL9h76WuyrF57mp5U7M4Rr/Vk6qHCJlygvPes0b3/59Otj3R2KyGlqZNNukiw+dolHL0fADYmzvyBSuVivyf/fmNzWoR37Z9c3CRGwandqmgMAdBhGIsCMkV+OBEX5Yff7oVC0H6JrPwi1WcJus1Vej0V/KIcBuQKBgQDiDtgc5UdUhOVV0NHsZXL9ubtLsUnOfBftlnqWSjTCzIsTRSSTSUR1XqEDnOB7TH3MnEnuO+V+eQrMebTnOhZ86pzrvgsBIwZUaXHBX+TOvXC1QgYv9ikgM3YpICOhMxHWvoWjfOY9WHZu8Be8emmtM+GBrum/y38V5KSXZXbfHwKBgQChd8/sv5UDyxsatF6D9MXjoEf2lW1Yz6QhznOccrKEjFs3d66XVFPCYBZ7s37gOaaX/yZhvtZgKvQjpe7OwVyMYmrcSNvcFc7a1kxvYETKNSesLviseUSsiMQ/YGC1NeWX2tChSZ06nr3b9xcv9I5+uUnnK9RUYakvjQh+8PIEzwKBgDbjldQGU/iQwELDDoXQ6Ef1ViX96Ubq2MCGvkNJx1/ZXJeUPVpJ+wZosL341IT7wLvy4vymrIW2DEoz7xoJ/7XbHbkcDv36rCnI5Kcoip0sYHaSjoAMzFWWSUWZGS2mAdnbrwVQaXNRzIgJYioQqyI0K7haaUV5uuTs/I4KQ//PAoGAKHXDTkm7Z1XvlsN3o40kQSOapLlQyx5MvIPlCGDdRsV83etJfnYM/vng6GJT+o+3pQK0dW3CfhqFTqF3s6tUK4FF0akYHpAAY2mrgYUX96tWI5kpit5gTPOAaXkXApFc1K5p9OBjW5sHbCUAVG3tfuejEyAydmp6YIXwiQ6LNpUCgYEAq05jgBjyw84ftOLN86dFVnvCudj9795X/MizGDh807NxBcc7tMf5YDj0hdeImsSp3hDJf/OwTOFafxNde5PL8ETrvj2J5URgQmrObzTzEdQy45ttuf3drXlxLlL7Ls9J5PzivLOLrXnDJyhM9vv2jEhwfkwBRtZVGa22HNOsUq4=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyYV6N/khn1sKIPxXHtPT/IVHbHCM21kGEsgjDKZ6zor9jdWlou7vpr5wgvkruQuGPjz9nPnXY0jpmxuPSphGbKCALelziRZehGAPovZvTEV1/gSNhQlyeZHPhpko73U64HIIPxPQJfZNTnIN+NcLw1mpxMrv2lcKH5352pn/7qt9LD2oKYQCqeT9d2qb85Ul6iJR0KAtFE1M7XCprNAecBbYx58mYQYvm0GmVcJO8OzU4qo1YfnskBVwqcBiZHt38/zqDdi530Yu+P8KF7kcqxjBo1dBWjkF/4oxqN6799mso/OSICcWfBdM0CtSB5ene4zPqq5A0JGHTYpaipCLBQIDAQAB
  notify-url: http://syvn9v.natappfree.cc/alipay/notify
  return-url: http://syvn9v.natappfree.cc/alipay/result

advertisement:
  daily-limit: 5  # 每日广告观看上限



#myStaticLocation: "/src/main/resources/static/"

